accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutPage, name='logout'),
    path('profile', views.profilePage, name='profile'),
    path('change/', views.changePage, name='change'),      # Update Form
    path('register', views.registerPage, name='register')  # Register Form
]

consultations/urls.py
from django.urls import path

from . import views

app_name = 'consultations'
urlpatterns = [
    #  /consultations/
    path('', views.index, name='index'),
    path('<int:consultation_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),                        # Add Form
    path('change/<int:consultation_id>/', views.change, name='change'),                # Update Form
    path('pricing/', views.pricing, name='pricing'),
    path('faq/', views.faq, name='faq'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact')
]

djangoconsultations/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('consultations/', include('consultations.urls')),  # allows referencing other urls.py file
    path('accounts/', include('accounts.urls'))             # allows referencing other urls.py file
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

consultations/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class Consultation(models.Model):
    SEX_CHOICES = [('M', 'Male'), ('F', 'Female')]
    SLEEP_CHOICES = [('B', 'Bad'), ('R', 'Regular'), ('G', 'Good')]
    STRESSLEVEL_CHOICES = [('L', 'Low'), ('M', 'Medium'), ('H', 'High')]
    DEFECATION_CHOICES = [('<1', 'Less than one'), ('1', 'Once'), ('2', 'Twice'), ('3', 'Thrice'), ('>3', 'More than thrice')]
    STATUS_CHOICES = [('Open', 'Open'), ('Closed', 'Closed'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'),
                      ('Waiting for Patient', 'Waiting for Patient'), ('Waiting for Payment', 'Waiting for Payment')]

    requester = models.ForeignKey(User, on_delete=models.CASCADE, related_name='consultations_created')
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='consultations_assigned', blank=True, null=True)

    timestamp = models.DateTimeField(default=datetime.now)
    age = models.IntegerField('Patient age')
    sex = models.CharField('Patient sex', max_length=1, choices=SEX_CHOICES)
    height = models.IntegerField('Height in cm')
    weight = models.IntegerField('Weight in kg')
    avg_waking_temp = models.FloatField('Average waking temperature in centigrades')
    avg_waking_pulse = models.IntegerField('Average waking pulse')
    avg_afternoon_temp = models.FloatField('Average afternoon temperature in centigrades')
    avg_afternoon_pulse = models.IntegerField('Average afternoon pulse')
    avg_sys_bp = models.IntegerField('Average systolic blood pressure')
    avg_dias_bp = models.IntegerField('Average diastolic blood pressure')
    bodyfat = models.FloatField('Body fat percentage')
    country = models.CharField('Country of residence', max_length=64)
    city = models.CharField('City of residence', max_length=64)
    avg_artificial_light = models.IntegerField('Average hours under artificial blue light')
    avg_sleep_hours = models.FloatField('Average hours of sleep per night')
    avg_sleep_quality = models.CharField('Energy level after sleeping', max_length=1, choices=SLEEP_CHOICES)
    stresslevel = models.CharField('Level of daily stress', max_length=1, choices=STRESSLEVEL_CHOICES)
    workhours = models.IntegerField('Work hours per day')
    bowelmovements = models.CharField('Average bowel movements per day', max_length=2, choices=DEFECATION_CHOICES, default='1')
    alcohol_use = models.TextField('Alcohol Consumption', blank=True)
    previous_conditions = models.TextField('Previous diagnosed conditions', blank=True)
    family_history = models.TextField('Family diagnosed conditions', blank=True)
    current_medications = models.TextField('Current drugs or medications', blank=True)
    current_symptoms = models.TextField('Current Symptoms', blank=True)
    expectations = models.TextField()

    status = models.CharField('Case status', max_length=32, choices=STATUS_CHOICES, default='Open')
    price = models.IntegerField('Price in USD', null=True)
    paymentinfo = models.TextField('Payment information', blank=True)


class UploadedFile(models.Model):
    # Uploaded files related to a Consultation - One to Many
    consultation = models.ForeignKey(Consultation, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    filecontent = models.FileField('File', upload_to='uploads/')


class Message(models.Model):
    consultation = models.ForeignKey(Consultation, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

consultations/forms.py
from django import forms
from .models import Consultation


class ConsultationForm(forms.ModelForm):
    class Meta:
        model = Consultation
        fields = [
            'age',
            'sex',
            'height',
            'weight',
            'avg_waking_temp',
            'avg_waking_pulse',
            'avg_afternoon_temp',
            'avg_afternoon_pulse',
            'avg_sys_bp',
            'avg_dias_bp',
            'bodyfat',
            'country',
            'city',
            'avg_artificial_light',
            'avg_sleep_hours',
            'avg_sleep_quality',
            'stresslevel',
            'workhours',
            'bowelmovements',
            'alcohol_use',
            'previous_conditions',
            'family_history',
            'current_medications',
            'current_symptoms',
            'expectations'
        ]

consultations/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseForbidden
from datetime import datetime
from django.db import transaction, IntegrityError

from django.contrib.auth.models import User
from django.contrib import messages
from .models import Consultation, UploadedFile, Message
from .forms import ConsultationForm

from .decorators import unauthenticated_user, allowed_users
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['requesters', 'agents', 'supervisors'])
def index(request):
    # Show consultations created by authenticated requester or all of them for the agents and supervisors
    if request.user.groups.filter(name='requesters').exists():
        print(request.user.username)
        consultations = Consultation.objects.filter(requester_id=request.user.id)
    else:
        consultations = Consultation.objects.all()
    open_consultations = consultations.filter(status='Open')
    pending_consultations = consultations.filter(status='Pending')
    waiting_for_patient_consultations = consultations.filter(status='Waiting for Patient')
    waiting_for_payment_consultations = consultations.filter(status='Waiting for Payment')
    closed_consultations = consultations.filter(status='Closed')
    resolved_consultations = consultations.filter(status='Resolved')
    rejected_consultations = consultations.filter(status='Rejected')
    context = {'consultations': consultations, 'open_consultations': open_consultations,
               'pending_consultations': pending_consultations,
               'waiting_for_patient_consultations': waiting_for_patient_consultations, 'waiting_for_payment_consultations': waiting_for_payment_consultations,
               'closed_consultations': closed_consultations, 'resolved_consultations': resolved_consultations, 'rejected_consultations': rejected_consultations
               }

    return render(request, 'index.html', context)


@login_required(login_url='accounts:login')
def detail(request, consultation_id):
    consultation = get_object_or_404(Consultation, id=consultation_id)
    if request.user.id == consultation.requester_id or request.user.groups.filter(name='supervisors').exists() or request.user.groups.filter(name='agents').exists():
        requester = get_object_or_404(User, id=consultation.requester_id)
        uploadedfiles = UploadedFile.objects.filter(consultation=consultation_id)
        chat = Message.objects.filter(consultation_id=consultation_id)

        context = {
            'consultation': consultation,
            'requester': requester,
            'uploadedfiles': uploadedfiles,
            'chat': chat
        }
        #  if the authenticated user is a requester
        if request.user.groups.filter(name='requesters').exists():
            context['UserIsStaff'] = False

        #  if the authenticated user is a supervisor or agent
        else:
            if request.user.groups.filter(name='supervisors').exists() or request.user.groups.filter(name='agents').exists():
                context['UserIsStaff'] = True

        if request.method == 'POST':
            if request.POST.get("send-message") == "send":
                if request.POST.get("chat-message"):
                    if len(request.POST.get("chat-message")) > 0:
                        newMessage = Message(consultation_id=consultation_id, sender_id=request.user.id, text=request.POST.get("chat-message"))
                        newMessage.save()
                        messages.success(request, "Message sent")
                else:
                    messages.error(request, "Chat Messages can't be empty")

            else:
                if request.POST.get("assignConsultation"):
                    consultation.assigned_to = request.user
                    consultation.save()
                    messages.success(request, "Consultation is assigned to you. Please make sure to respond within 48 Hours")
                if request.POST.get("price") and consultation.price != int(request.POST.get("price")) and int(request.POST.get("price")) >= 0:
                    consultation.price = int(request.POST.get("price"))
                    consultation.save()
                    messages.success(request, "Price was set. Send the payment information to the \
                        user, when payment is confirmed, add this to payment information and save it")
                if request.POST.get("paymentInfo") and consultation.paymentinfo != request.POST.get("paymentInfo"):
                    consultation.paymentinfo = request.POST.get("paymentInfo")
                    consultation.save()
                    messages.success(request, "Payment info submitted. Wait for a payment hash or tx number to verify it.")
                if consultation.status != request.POST.get("status") and request.POST.get("status") is not None:
                    consultation.status = request.POST.get("status")
                    consultation.save()
                    messages.success(request, "Status changed")

            return render(request, 'detail.html', context)
        #  request.method not POST
        else:
            return render(request, 'detail.html', context)
    else:
        return HttpResponseForbidden('<h1>403 Forbidden</h1><p>You have no access to this site</p>', content_type='text/html')


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['requesters', 'supervisors'])
def add(request):
    form = ConsultationForm(request.POST or None)
    UploadedFileFormset = modelformset_factory(UploadedFile, exclude=('consultation',), extra=5, max_num=5)
    formset = UploadedFileFormset(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    consultation = form.save(commit=False)
                    consultation.requester_id = request.user.id
                    consultation.save()
                    for upload in formset:
                        #  prevent saving empty forms as uploads
                        if upload.cleaned_data != {}:
                            data = upload.save(commit=False)
                            data.consultation = consultation
                            data.save()
            except IntegrityError:
                messages.success(request, "Error found while saving form. Check your information or contact web admin")

            messages.success(request, 'Your consultation is created and an advisor will write you back soon')
            return redirect('consultations:index')
        else:
            messages.error(request, "There are errors in your consultation form. Check your information")

            context = {
                'form': form,
                'formset': formset
            }
            return render(request, 'add.html', context)
    else:
        formset = UploadedFileFormset(queryset=UploadedFile.objects.none())
        context = {
            'form': form,
            'formset': formset
        }
        return render(request, 'add.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['requesters', 'supervisors'])
def change(request, consultation_id):
    consultation = get_object_or_404(Consultation, id=consultation_id)
    if request.user.id == consultation.requester_id:
        if request.method == 'POST':
            form = ConsultationForm(request.POST, instance=consultation)
            UploadedFileFormset = modelformset_factory(UploadedFile, exclude=('consultation',), extra=5, max_num=5)
            formset = UploadedFileFormset(request.POST or None, request.FILES or None)
            if form.is_valid() and formset.is_valid():
                try:
                    with transaction.atomic():
                        consultation = form.save(commit=False)
                        consultation.requester_id = request.user.id
                        consultation.save()
                        for upload in formset:
                            if upload.cleaned_data != {}:  # prevent saving empty forms as uploads
                                data = upload.save(commit=False)
                                data.consultation = consultation
                                data.save()
                except IntegrityError:
                    messages.success(request, "Error found while saving form. Check your information or contact web admin")

                messages.success(request, "Your consultation was saved and an advisor will write you back soon")
                return redirect('consultations:index')
            else:
                messages.error(request, "There are errors in your consultation form. Check your information")

                context = {
                    'form': form,
                    'formset': formset
                }
                return render(request, 'add.html', context)
        else:
            UploadedFileFormset = modelformset_factory(UploadedFile, exclude=('consultation',), extra=5, max_num=5)
            form = ConsultationForm(instance=consultation)
            formset = UploadedFileFormset(queryset=UploadedFile.objects.filter(consultation=consultation_id))
            context = {
                'form': form,
                'formset': formset
            }
            return render(request, 'change.html', context)
    else:
        return HttpResponseForbidden('<h1>403 Forbidden</h1><p>You have no access to this site</p>', content_type='text/html')


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['requesters', 'supervisors'])
def delete(request, consultation_id):
    consultation = get_object_or_404(Consultation, id=consultation_id)

consultations/templates/add.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container-fluid">
    <h1>Add consultation</h1>
</div>
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endif %}	
    {% endfor %}
{% endif %}

<div class="container-fluid">   
    <form method="post" enctype="multipart/form-data" action="" id="consultation_form" novalidate="">
        {% csrf_token %}
        <div>

            {{ form.as_p }}
        
            {{ formset.management_form }}
            <table>
                {% for uploadform in formset %}
                    {{ uploadform }}
                {% endfor %}
            </table>



            <br>
            <div class="submit-row">

            <input type="submit" value="Save" class="btn btn-success" name="_save">
            <a href="{% url 'consultations:index' %}" class="btn btn-secondary">Cancel</a>

            </div>

        </div>
    </form>
</div>

    
    <br class="clear">
  </div>

{% endblock %}

consultations/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Django Consultations</title>
  </head>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">

  <body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
        <img src="{% static '/images/logo.jpeg' %}" width="80" height="80" class="d-inline-block align-top" alt="">
        Django Consultations
        </a>
    </nav>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile' %}">My Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:index' %}">Consultations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:pricing' %}">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:faq' %}">F.A.Q.</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:terms' %}">Terms and Conditions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:contact' %}">Contact us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Log out </a>
            </li>
        </ul>
        </div>
    </nav>
    <br>
    
    {% block content %}
    {% endblock %}

    <br>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Django Consultations is a website demo, is not intended to be medical advice, therefore are NOT responsible for any interaction within this website</span>
    </nav>

  <body>

</html>

consultations/templates/contact.html
{% extends "base_generic.html" %}

{% block content %}

<h3>Contact us at: email@example.com</h3>

{% endblock %}

consultations/templates/detail.html
{% extends "base_generic.html" %}
{% load static %}
  
{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endif %}	
    {% endfor %}
{% endif %}

<h1>Consultation Number {{ consultation.id }}</h1>

<div class="container-fluid">   
    <h2>Details</h2>
        <table class="table">
            <tbody>
                <tr>
                <th>ID</th>
                    <td>{{ consultation.id }}</td>
                </tr>
                <tr>
                <th>Timestamp</th>
                    <td>{{ consultation.timestamp }}</td>
                </tr>
                <th>Name</th>
                <td>{{ requester.first_name }} {{ requester.last_name }}</td>
                </tr>
                <tr>
                <th>Age</th>
                    <td>{{ consultation.age }}</td>
                </tr>
                <tr>
                <th>Sex</th>
                    <td>{{ consultation.sex }}</td>
                </tr>
                <tr>
                <th>Height</th>
                    <td>{{ consultation.height }} cm</td>
                </tr>
                <tr>
                <th>Weight</th>
                    <td>{{ consultation.weight }} Kg</td>
                </tr>
                <tr>
                <th>Avg. Waking Temp.</th>
                    <td>{{ consultation.avg_waking_temp }} ºC</td>
                </tr>
                <tr>
                <th>Avg. Waking Pulse</th>
                    <td>{{ consultation.avg_waking_pulse }} ppm</td>
                </tr>
                <tr>
                <th>Avg. Afternoon Temp.</th>
                    <td>{{ consultation.avg_afternoon_temp }} ºC</td>
                </tr>
                <tr>
                <th>Avg. Afternoon Pulse</th>
                    <td>{{ consultation.avg_afternoon_pulse }} ppm</td>
                </tr>
                <tr>
                <th>Avg. Sys. Blood Pressure</th>
                    <td>{{ consultation.avg_sys_bp }} mmHg</td>
                </tr>
                <tr>
                <th>Avg. Dias. Blood Pressure</th>
                    <td>{{ consultation.avg_dias_bp }} mmHg</td>
                </tr>
                <tr>
                <th>Bodyfat percentage</th>
                    <td>{{ consultation.bodyfat }} %</td>
                </tr>
                <tr>
                <th>Country</th>
                    <td>{{ consultation.country }}</td>
                </tr>
                <tr>
                <th>City</th>
                    <td>{{ consultation.city }}</td>
                </tr>
                <tr>
                <th>Avg. Artificial Light per day</th>
                    <td>{{ consultation.avg_artificial_light }} Hours</td>
                </tr>
                <th>Avg. Sleep per day</th>
                    <td>{{ consultation.avg_sleep_hours }} Hours</td>
                </tr>
                <th>Avg. Sleep quality</th>
                    <td>{{ consultation.avg_sleep_quality }}</td>
                </tr>
                <th>Stress Level</th>
                    <td>{{ consultation.stresslevel }}</td>
                </tr>
                <th>Work per day</th>
                    <td>{{ consultation.workhours }} Hours</td>
                </tr>
                <th>Alcohol consumption</th>
                    <td>{{ consultation.alcohol_use }}</td>
                </tr>
                <th>Bowel movements</th>
                    <td>{{ consultation.bowelmovements }} per day</td>
                </tr>
                <th>Previous Conditions</th>
                    <td>{{ consultation.previous_conditions }}</td>
                </tr>
                <th>Family History</th>
                    <td>{{ consultation.family_history }}</td>
                </tr>                
                <th>Current Medications</th>
                    <td>{{ consultation.current_medications }}</td>
                </tr>
                <th>Current Symptoms</th>
                    <td>{{ consultation.current_symptoms }}</td>
                </tr>                
                <th>Expectations</th>
                    <td>{{ consultation.expectations }}</td>
                </tr>
                <th>Uploads</th>
                    {% for file in uploadedfiles %}
                        <td>{{ file.description }}</td>
                        <td><a href="http://{{ request.get_host }}/media/{{ file.filecontent }}">http://{{ request.get_host }}/media/{{ file.filecontent }}</a></td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
        <br>
        <table class="table">
            <th>Status</th>
            <td>{{ consultation.status }}</td>
            </tr>
            <th>Adviser</th>
                <td>{{ consultation.assigned_to }}</td>
            </tr>
        </table>
        <br>
        <h3>Payment</h3>
        <table class="table">
            <th>Price</th>
            <td>{% if consultation.price == None %} Not set yet {% else %} {{ consultation.price }} USD {% endif %} </td>
            </tr>
            <th>Payment Information</th>
                <td>{{ consultation.paymentinfo }}</td>
            </tr>
        </table>
</div> 
<div id="chatDiv" class="container-fluid">   
    <h2>Messages</h2>
    {% if chat %}
        <table class="table">
            <thead class="thead-light">
            <tr class="d-flex">
                <th scope="col" class="col-2">Received at</th>
                <th scope="col" class="col-2">User</th>
                <th scope="col" class="col-8">Message</th>
            </tr>
            </thead>
            <tbody>
            {% for msg in chat %}
            <tr class="d-flex">
                <td scope="col" class="col-2">{{ msg.timestamp }}</th>
                <td class="col-2">{{msg.sender }}</td>
                <td class="col-8">{{msg.text }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">No messages yet. Replies usually takes up to 2 weekdays.</th>
            </tr>
            </thead>
        </table>
    {% endif %}
    <div class="container-fluid">
        <form method="post" action="#">
            {% csrf_token %}
            <div class="form-group">
                <label for="chatText">Text:</label>
                <input type="text" class="form-control" id="chatText" name="chat-message" minlength="1"></textarea>
            </div>
            <button type="submit" class="btn btn-primary" name="send-message" value="send">Send Message</button>
        </form>
    </div>
</div> 
<br>

{% if UserIsStaff %}
<form method="post" action="" id="ConsultationStaffForm">
    {% csrf_token %}
    <div class="container-fluid">
        {% if consultation.assigned_to == Null %}
            <h3>Take Consultation</h3>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="assignConsultation" name="assignConsultation" value="True">
                <label class="form-check-label" for="assignConsultation">Yes</label>
            </div>
            <br>
        {% endif %}
        <h3>Set Status</h3>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="statusOpen" value="Open" disabled {% if consultation.status == 'Open' %} checked {% endif %}>
            <label class="form-check-label" for="status0">
            Open
            </label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="statusPending" value="Pending" {% if consultation.status == 'Pending' %} checked {% endif %}>
            <label class="form-check-label" for="status1">
            Pending
            </label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="statusWaitingForPatient" value="Waiting for Patient" {% if consultation.status == 'Waiting for Patient' %} checked {% endif %}>
            <label class="form-check-label" for="status2">
            Waiting for Patient
            </label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="statusWaitingForPayment" value="Waiting for Payment" {% if consultation.status == 'Waiting for Payment' %} checked {% endif %}>
            <label class="form-check-label" for="status3">
            Waiting for Payment
            </label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="statusResolved" value="Resolved" {% if consultation.status == 'Resolved' %} checked {% endif %}>
            <label class="form-check-label" for="status4">
            Resolved
            </label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="status" id="statusRejected" value="Rejected" {% if consultation.status == 'Rejected' %} checked {% endif %}>
            <label class="form-check-label" for="status5">
            Rejected
            </label>
        </div>
        <div class="form-group">
            <label for="paymentInfo">Payment Info:</label>
            <input type="text" class="form-control" id="paymentInfo" name="paymentInfo" minlength="1" placeholder="Account, currency, amount equivalency or anything necessary to pay" value="{{ consultation.paymentinfo }}"></textarea>
            <label for="price">Payment Amount in USD:</label>
            <input type="number" class="form-control" id="price" name="price" min="0" value="{{ consultation.price }}">
        </div> 
    </div>

    <br>

    <div class="container-fluid">
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-4" role="group" aria-label="First group">
                <input type="submit" value="Save" class="btn btn-success" name="_save">
                <a href="{% url 'consultations:index' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </div>
    </div>
</form>

{% else %}
<div class="container-fluid">
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group mr-4" role="group" aria-label="First group">
            <button type="button" class="btn btn-light" onclick="location.href='{% url 'consultations:change' consultation.id %}'">Edit</button>
        </div>
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="Second group">
            <button type="button" class="btn btn-danger" onclick="if (confirm('Are you sure you want to delete the consultation?')){window.location = './delete'}">Delete Consultation</button>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}