accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutPage, name='logout'),
    path('profile', views.profilePage, name='profile'),
    path('change/', views.changePage, name='change'),      # Update Form
    path('register', views.registerPage, name='register')  # Register Form
]

consultations/urls.py
from django.urls import path

from . import views

app_name = 'consultations'
urlpatterns = [
    #  /consultations/
    path('', views.index, name='index'),
    path('<int:consultation_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),                        # Add Form
    path('change/<int:consultation_id>/', views.change, name='change'),                # Update Form
    path('pricing/', views.pricing, name='pricing'),
    path('faq/', views.faq, name='faq'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact')
]

djangoconsultations/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('consultations/', include('consultations.urls')),  # allows referencing other urls.py file
    path('accounts/', include('accounts.urls'))             # allows referencing other urls.py file
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Django Consultations</title>
  </head>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">

  <body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
        <img src="{% static '/images/logo.jpeg' %}" width="80" height="80" class="d-inline-block align-top" alt="">
        Django Consultations
        </a>
    </nav>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile' %}">My Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:index' %}">Consultations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:pricing' %}">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:faq' %}">F.A.Q.</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:terms' %}">Terms and Conditions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'consultations:contact' %}">Contact us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Log out </a>
            </li>
        </ul>
        </div>
    </nav>
    <br>
    
    <div class="container-fluid">
        <p>Welcome to Django Consultations</p>
    </div>

    <br>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Django Consultations is a website demo, is not intended to be medical advice, therefore are NOT responsible for any interaction within this website</span>
    </nav>

  <body>

</html>